
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/login_check

# config\routes.yaml
controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# email_send:
#     path: '/contact'
#     controller: 'App\Controller\ContactController::sendEmail'
#     methods: ['POST']
